version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: webproject
      DB_USERNAME: eliza
      DB_PASSWORD: parola
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: webproject
      MYSQL_USER: eliza
      MYSQL_PASSWORD: parola
      MYSQL_ROOT_PASSWORD: parola
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

